import GlobalContextProvider from "@/state/context/GlobalContext";
import "./globals.css";
import { Raleway } from "next/font/google";
import { MantineProvider } from "@mantine/core";
const raleway = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        {/* <GlobalContextProvider> */}
        <MantineProvider>{children}</MantineProvider>
        {/* </GlobalContextProvider> */}
      </body>
    </html>
  );
}
